name: render_kit
description: A declarative UI compilation framework that translates custom Dart DSL widgets into native Kotlin Jetpack Compose and Swift SwiftUI source code.
version: 1.0.0
homepage: https://github.com/mohammed-fawaz-cp/renderkit
repository: https://github.com/mohammed-fawaz-cp/renderkit
issue_tracker: https://github.com/mohammed-fawaz-cp/renderkit/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  renderkit:
    path: ./renderkit
  renderkit_annotations:
    path: ./renderkit_annotations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
