name: render_kit_flutter
description: A declarative UI compilation framework that translates custom Dart DSL widgets into native Kotlin Jetpack Compose and Swift SwiftUI source code.
version: 1.1.1
homepage: https://github.com/mohammed-fawaz-cp/render_kit_flutter
repository: https://github.com/mohammed-fawaz-cp/render_kit_flutter
issue_tracker: https://github.com/mohammed-fawaz-cp/render_kit_flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  renderkit: ^0.1.0
  renderkit_annotations: ^0.1.0

dependency_overrides:
  renderkit:
    path: ./renderkit
  renderkit_annotations:
    path: ./renderkit_annotations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mohammed_fawaz_cp.render_kit_flutter
        pluginClass: RenderKitFlutterPlugin
      ios:
        pluginClass: RenderKitFlutterPlugin

