name: renderkit
description: Custom DSL and Flutter preview components for RenderKit.
version: 0.1.0
homepage: https://github.com/mohammed-fawaz-cp/render_kit_flutter/tree/main/renderkit
repository: https://github.com/mohammed-fawaz-cp/render_kit_flutter
issue_tracker: https://github.com/mohammed-fawaz-cp/render_kit_flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  renderkit_annotations: ^0.1.0

dependency_overrides:
  renderkit_annotations:
    path: ../renderkit_annotations
