name: renderkit
description: Custom DSL and Flutter preview components for RenderKit.
version: 0.1.0
homepage: https://github.com/renderkit/render_kit/tree/main/renderkit
repository: https://github.com/renderkit/render_kit
issue_tracker: https://github.com/renderkit/render_kit/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  renderkit_annotations:
    path: ../renderkit_annotations
