name: renderkit_annotations
description: Annotations for the RenderKit cross-platform UI compiler.
version: 0.1.0
homepage: https://github.com/mohammed-fawaz-cp/render_kit_flutter/tree/main/renderkit_annotations
repository: https://github.com/mohammed-fawaz-cp/render_kit_flutter
issue_tracker: https://github.com/mohammed-fawaz-cp/render_kit_flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
