name: renderkit_cli
description: CLI tool for RenderKit to validate environments, configure pipelines, and compile widgets.
version: 0.1.3
homepage: https://github.com/mohammed-fawaz-cp/render_kit_flutter/tree/main/renderkit_cli
repository: https://github.com/mohammed-fawaz-cp/render_kit_flutter
issue_tracker: https://github.com/mohammed-fawaz-cp/render_kit_flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.0
  path: ^1.8.0
  io: ^1.0.0
